// =============================================================================
// LiteVO version information — generated by CMake from version.h.in
// =============================================================================

#pragma once

#define LITEVO_VERSION_MAJOR 2
#define LITEVO_VERSION_MINOR 0
#define LITEVO_VERSION_PATCH 0
#define LITEVO_VERSION_STRING "2.0.0"

namespace litevo {

/// Major version number.
constexpr int kVersionMajor = 2;

/// Minor version number.
constexpr int kVersionMinor = 0;

/// Patch version number.
constexpr int kVersionPatch = 0;

/// Full version string (e.g., "2.0.0").
constexpr const char* kVersionString = "2.0.0";

}  // namespace litevo
