// =============================================================================
// SLAMForge map export implementation
// =============================================================================

#include "slamforge/io/map_export.h"

#include <Eigen/Core>

#include <fstream>
#include <iomanip>
#include <vector>

#include "slamforge/core/map.h"
#include "slamforge/core/map_point.h"

namespace slamforge::io {

MapExportResult ExportMapAsPly(const Map& map, const std::filesystem::path& output_path) {
    MapExportResult result;
    if (output_path.empty()) {
        result.error = "map output path is empty";
        return result;
    }

    std::vector<Vec3> positions;
    {
        auto graph_lock = map.AcquireGraphLock();
        const auto map_points = map.GetAllMapPoints();
        positions.reserve(map_points.size());
        for (const auto& map_point : map_points) {
            if (!map_point || map_point->IsBad()) {
                continue;
            }
            const Vec3 position = map_point->Position();
            if (position.allFinite()) {
                positions.push_back(position);
            }
        }
    }

    std::ofstream output(output_path, std::ios::out | std::ios::trunc);
    if (!output.is_open()) {
        result.error = "cannot open map output '" + output_path.string() + "'";
        return result;
    }

    output << "ply\n"
           << "format ascii 1.0\n"
           << "comment Generated by SLAMForge\n"
           << "element vertex " << positions.size() << "\n"
           << "property double x\n"
           << "property double y\n"
           << "property double z\n"
           << "end_header\n";
    output << std::setprecision(17);
    for (const Vec3& position : positions) {
        output << position.x() << ' ' << position.y() << ' ' << position.z() << '\n';
    }

    if (!output) {
        result.error = "failed while writing map output '" + output_path.string() + "'";
        return result;
    }

    result.success = true;
    result.point_count = positions.size();
    return result;
}

}  // namespace slamforge::io
